import { makeStyles, shorthands, tokens } from '@fluentui/react-components';

export const useScatterPlotStyles = makeStyles({
    root: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
        backgroundColor: tokens.colorNeutralBackground1,
        borderRadius: tokens.borderRadiusMedium,
        ...shorthands.padding(0),
    },
    header: {
        backgroundColor: tokens.colorBrandBackground,
        color: tokens.colorBrandBackgroundInverted,
        borderRadius: tokens.borderRadiusMedium,
        ...shorthands.padding(tokens.spacingVerticalM),
        marginBottom: tokens.spacingVerticalXS,
    },
    headerTitleRow: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
        marginBottom: tokens.spacingVerticalXS,
    },
    headerSubtitle: {
        color: tokens.colorBrandBackgroundInverted,
        opacity: 0.9,
    },
    sectionCard: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
        ...shorthands.padding(tokens.spacingVerticalM),
        backgroundColor: tokens.colorNeutralBackground2,
        borderRadius: tokens.borderRadiusMedium,
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    },
    simpleCard: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
        ...shorthands.padding(tokens.spacingVerticalM),
        backgroundColor: tokens.colorNeutralBackground2,
        borderRadius: tokens.borderRadiusMedium,
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    },
    scatterConfiguration: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
        ...shorthands.padding(tokens.spacingVerticalM),
        backgroundColor: tokens.colorNeutralBackground2,
        borderRadius: tokens.borderRadiusMedium,
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    },
    sectionTitle: {
        color: tokens.colorNeutralForeground1,
        marginBottom: tokens.spacingVerticalXS,
    },
    variableContainer: {
        backgroundColor: tokens.colorNeutralBackground2,
        borderRadius: tokens.borderRadiusMedium,
        boxShadow: tokens.shadow2,
        overflow: 'hidden',
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    },
    variableHeader: {
        backgroundColor: tokens.colorNeutralBackground3,
        ...shorthands.padding(tokens.spacingVerticalM),
        ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralStroke2),
    },
    variableHeaderRow: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
    },
    variableHeaderTitle: {
        color: tokens.colorNeutralForeground1,
    },
    variableHeaderSubtitle: {
        color: tokens.colorNeutralForeground2,
        marginTop: tokens.spacingVerticalXS,
    },
    columns: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr 1fr',
        gap: 0,
        minHeight: '300px',
    },
    column: {
        backgroundColor: tokens.colorNeutralBackground3,
        ...shorthands.padding(tokens.spacingVerticalM),
        ...shorthands.borderRight('1px', 'solid', tokens.colorNeutralStroke2),
    },
    columnNoRightBorder: {
        backgroundColor: tokens.colorNeutralBackground3,
        ...shorthands.padding(tokens.spacingVerticalM),
    },
    columnHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: tokens.spacingVerticalS,
        paddingBottom: tokens.spacingVerticalXS,
        ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralStroke2),
    },
    columnHeaderTitle: {
        color: tokens.colorNeutralForeground1,
        fontWeight: 'bold',
        fontSize: '12px',
        textTransform: 'uppercase',
        letterSpacing: '0.5px',
    },
    columnHeaderBadge: {
        backgroundColor: tokens.colorBrandBackground,
        color: tokens.colorBrandBackgroundInverted,
        borderRadius: '50%',
        minWidth: '20px',
        height: '20px',
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        fontSize: '11px',
        fontWeight: 'bold',
    },
    actions: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalXS,
        marginTop: tokens.spacingVerticalM,
    },
    actionBtn: {
        fontSize: '12px',
        height: '28px',
        minWidth: '100px',
    },
    removeBtn: {
        fontSize: '12px',
        height: '28px',
        minWidth: '100px',
    },
    dropdown: {
        width: '100%',
    },
    loading: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        gap: tokens.spacingHorizontalM,
        ...shorthands.padding(tokens.spacingVerticalL),
    },
    loadingText: {
        color: tokens.colorNeutralForeground2,
    },
    error: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalM,
        ...shorthands.padding(tokens.spacingVerticalM),
        backgroundColor: tokens.colorPaletteRedBackground2,
        color: tokens.colorPaletteRedForeground1,
        borderRadius: tokens.borderRadiusMedium,
        ...shorthands.border('1px', 'solid', tokens.colorPaletteRedBorder1),
    },
});
