import { makeStyles, shorthands, tokens, Dropdown } from '@fluentui/react-components';

export const useToolStripLayout = makeStyles({
  layoutToolStrip: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    width: '100%',
    gap: tokens.spacingVerticalS,
  },
  titleSearch: {
    display: 'flex',
    flexDirection: 'row',
    width: '100%',
    backgroundColor: tokens.colorNeutralStencil2Alpha,
    padding: tokens.spacingVerticalSNudge,
    alignItems: 'center',
    justifyContent: 'space-between',
    fontWeight: 600,
    fontSize: 'small',
    textTransform: 'uppercase',
    ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralForegroundDisabled),
  },
  toolStrip: {
    display: 'grid',
    gridTemplateColumns: '3% 94% 3%',
    alignItems: 'center',
    justifyItems: 'center',
    backgroundColor: tokens.colorNeutralStencil2Alpha,
    padding: 0,
    width: '100%',
    overflow: 'hidden',
    ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralForegroundDisabled),
    ...shorthands.borderTop('1px', 'solid', tokens.colorNeutralForegroundDisabled),
  },
  dropDownSelection: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    fontWeight: 400,
    padding: tokens.spacingVerticalXS,
  },
  dropdownOptions: {
    ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralForegroundDisabled),
  },
  ul: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    listStyleType: 'none',
    padding: 0,
    margin: 0,
    overflowX: 'auto',
    whiteSpace: 'nowrap',
    scrollBehavior: 'smooth',
    width: 'calc(100% - 80px)',
    '& li': {
      flexShrink: 0,
      cursor: 'pointer',
      display: 'flex',
      overflowY: 'hidden',
      flexDirection: 'column',
      alignItems: 'center',
      height: '60px',
      '& div': {
        '& button': {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          alignContent: 'center',
          // padding: 0,
          padding: tokens.spacingVerticalM,
          margin: 0,
          '& span': {
            textAlign: 'center',
            width: '60px',
          },
        },
      },
      ':last-child': {
        ...shorthands.borderRight('1px', 'solid', tokens.colorNeutralForegroundDisabled),
      },
      ...shorthands.borderLeft('1px', 'solid', tokens.colorNeutralForegroundDisabled),
    },
    '::-webkit-scrollbar': {
      display: 'none',
    },
  },
  navButtons: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    height: '100%',
    backgroundColor: tokens.colorNeutralCardBackgroundPressed,
  },
});
