import { makeStyles, shorthands, tokens } from '@fluentui/react-components';

export const useGraphTabLayout = makeStyles({
  historyTab: {
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyItems: 'center',
    paddingTop: tokens.spacingVerticalS,
    height: '40px',
    width: '99.5%',
    paddingLeft: tokens.spacingHorizontalS,
  },
  ul: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    gap: tokens.spacingHorizontalS,
    listStyleType: 'none',
    padding: 0,
    margin: 0,
    overflowX: 'auto',
    whiteSpace: 'nowrap',
    scrollBehavior: 'smooth',
    backgroundColor: tokens.colorNeutralStencil2Alpha,
    scrollbarWidth: 'none',
    width: '100%',
    '& li': {
      flexShrink: 0,
      cursor: 'pointer',
      display: 'flex',
      overflowY: 'hidden',
      flexDirection: 'column',
      alignItems: 'center',
      height: '40px',
      '& div': {
        '& button': {
          display: 'flex',
          flexDirection: 'column',
          alignItems: 'center',
          alignContent: 'center',
          padding: tokens.spacingVerticalM,
          margin: 0,
          '& span': {
            textAlign: 'center',
            width: '60px',
          },
        },
      },
      ':last-child': {
        ...shorthands.borderRight('1px', 'solid', tokens.colorNeutralForegroundDisabled),
      },
      ...shorthands.borderLeft('1px', 'solid', tokens.colorNeutralForegroundDisabled),
    },
    '::-webkit-scrollbar': {
      display: 'none',
    },
  },
  navButtons: {
    width: '100%',
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
    // height: '100%',
    height: '40px',
    backgroundColor: tokens.colorNeutralCardBackgroundPressed,
  },
  docIndex: {
    display: 'flex',
    flexDirection: 'row',
    alignItems: 'center',
    justifyContent: 'center',
  },
});
