import { makeStyles, shorthands, tokens } from '@fluentui/react-components';

export const useBarPlotStyles = makeStyles({
    root: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalS,
        backgroundColor: tokens.colorNeutralBackground1,
        borderRadius: tokens.borderRadiusMedium,
        ...shorthands.padding(0),
    },
    header: {
        backgroundColor: tokens.colorBrandBackground,
        color: tokens.colorBrandBackgroundInverted,
        borderRadius: tokens.borderRadiusMedium,
        ...shorthands.padding(tokens.spacingVerticalM),
        marginBottom: tokens.spacingVerticalXS,
    },
    headerTitleRow: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
        marginBottom: tokens.spacingVerticalXS,
        '& *': { color: tokens.colorBrandBackgroundInverted },
    },
    headerSubtitle: {
        color: tokens.colorBrandBackgroundInverted,
        opacity: 0.9,
    },
    sectionCard: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr',
        gap: tokens.spacingHorizontalS,
        backgroundColor: tokens.colorNeutralBackground2,
        borderRadius: tokens.borderRadiusMedium,
        boxShadow: tokens.shadow2,
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
        ...shorthands.padding(tokens.spacingVerticalS),
    },
    dropdown: {
        minHeight: '40px',
        backgroundColor: tokens.colorNeutralBackground1,
    },
    simpleCard: {
        backgroundColor: tokens.colorNeutralBackground2,
        borderRadius: tokens.borderRadiusMedium,
        boxShadow: tokens.shadow2,
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
        ...shorthands.padding(tokens.spacingVerticalM),
    },
    loading: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'center',
        backgroundColor: tokens.colorNeutralBackground2,
        borderRadius: tokens.borderRadiusMedium,
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
        ...shorthands.padding(tokens.spacingVerticalXL),
    },
    loadingText: {
        marginLeft: tokens.spacingHorizontalS,
        color: tokens.colorNeutralForeground2,
    },
    error: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
        backgroundColor: tokens.colorPaletteRedBackground1,
        borderRadius: tokens.borderRadiusMedium,
        color: tokens.colorPaletteRedForeground1,
        ...shorthands.border('1px', 'solid', tokens.colorPaletteRedBorder1),
        ...shorthands.padding(tokens.spacingVerticalM),
    },
    variableContainer: {
        backgroundColor: tokens.colorNeutralBackground2,
        borderRadius: tokens.borderRadiusMedium,
        boxShadow: tokens.shadow2,
        overflow: 'hidden',
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
    },
    variableHeader: {
        backgroundColor: tokens.colorNeutralBackground3,
        ...shorthands.padding(tokens.spacingVerticalM),
        ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralStroke2),
    },
    variableHeaderRow: {
        display: 'flex',
        alignItems: 'center',
        gap: tokens.spacingHorizontalS,
    },
    variableHeaderTitle: {
        color: tokens.colorNeutralForeground1,
    },
    variableHeaderSubtitle: {
        color: tokens.colorNeutralForeground2,
        marginTop: tokens.spacingVerticalXS,
    },
    columns: {
        display: 'grid',
        gridTemplateColumns: '1fr 1fr 1fr',
        gap: 0,
        minHeight: '300px',
    },
    column: {
        backgroundColor: tokens.colorNeutralBackground3,
        ...shorthands.padding(tokens.spacingVerticalM),
        ...shorthands.borderRight('1px', 'solid', tokens.colorNeutralStroke2),
    },
    columnNoRightBorder: {
        backgroundColor: tokens.colorNeutralBackground3,
        ...shorthands.padding(tokens.spacingVerticalM),
    },
    columnHeader: {
        display: 'flex',
        alignItems: 'center',
        justifyContent: 'space-between',
        marginBottom: tokens.spacingVerticalS,
        paddingBottom: tokens.spacingVerticalXS,
        ...shorthands.borderBottom('1px', 'solid', tokens.colorNeutralStroke2),
    },
    columnHeaderTitle: {
        color: tokens.colorNeutralForeground1,
    },
    columnHeaderBadge: {
        backgroundColor: tokens.colorNeutralForeground2,
        color: tokens.colorNeutralBackground1,
        borderRadius: tokens.borderRadiusCircular,
        fontSize: '12px',
        fontWeight: 500,
        ...shorthands.padding('2px', '8px'),
    },
    actions: {
        display: 'flex',
        flexDirection: 'column',
        gap: tokens.spacingVerticalXS,
        marginTop: tokens.spacingVerticalM,
    },
    actionBtn: {
        width: '100%',
        backgroundColor: tokens.colorNeutralBackground1,
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
        color: tokens.colorNeutralForeground1,
    },
    removeBtn: {
        width: '100%',
        marginTop: tokens.spacingVerticalM,
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
        color: tokens.colorNeutralForeground2,
    },
    createSection: {
        display: 'flex',
        justifyContent: 'flex-end',
        backgroundColor: tokens.colorNeutralBackground2,
        borderRadius: tokens.borderRadiusMedium,
        boxShadow: tokens.shadow2,
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
        ...shorthands.padding(tokens.spacingVerticalM),
        marginTop: tokens.spacingVerticalM,
    },
    createBtn: {
        minWidth: '160px',
        height: '48px',
        fontSize: '16px',
        fontWeight: 600,
    },
    listHeader: {
        display: 'flex',
        justifyContent: 'space-between',
        alignItems: 'center',
        marginBottom: tokens.spacingVerticalS,
        backgroundColor: tokens.colorNeutralBackground1,
        borderRadius: tokens.borderRadiusSmall,
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
        ...shorthands.padding(tokens.spacingVerticalXS),
    },
    listBadge: {
        fontSize: '12px',
        color: tokens.colorNeutralForeground2,
        fontWeight: 600,
        backgroundColor: tokens.colorNeutralBackground2,
        borderRadius: tokens.borderRadiusCircular,
        ...shorthands.padding('2px', '8px'),
    },
    listContainer: {
        maxHeight: '200px',
        overflowY: 'auto',
        backgroundColor: tokens.colorNeutralBackground1,
        borderRadius: tokens.borderRadiusSmall,
        ...shorthands.border('1px', 'solid', tokens.colorNeutralStroke2),
        ...shorthands.padding(tokens.spacingVerticalXS),
    },
    listItem: {
        marginBottom: tokens.spacingVerticalXS,
        borderRadius: tokens.borderRadiusSmall,
        transitionProperty: 'all',
        transitionDuration: '0.2s',
        transitionTimingFunction: 'ease',
    },
    listEmpty: {
        textAlign: 'center',
        color: tokens.colorNeutralForeground2,
        fontStyle: 'italic',
        fontSize: '14px',
        ...shorthands.padding(tokens.spacingVerticalM),
    },
});
