import { makeStyles, tokens } from '@fluentui/react-components';

export const useSampleSizeStyles = makeStyles({
  sampleSizeWrapper: {
    minWidth: '500px',
    maxWidth: '600px',
    padding: '0',
  },
  formContainer: {
    display: 'flex',
    flexDirection: 'column',
    gap: '20px',
  },
  inputRow: {
    display: 'grid',
    gridTemplateColumns: '1fr 1fr',
    gap: '16px',
    alignItems: 'end',
  },
  inputField: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
    minWidth: '0', // Ensures equal width
  },
  inputGroup: {
    display: 'flex',
    flexDirection: 'column',
    gap: '8px',
  },
  label: {
    fontWeight: '600',
    fontSize: '14px',
    color: tokens.colorNeutralForeground1,
    marginBottom: '4px',
  },
  input: {
    width: '100%',
    minHeight: '32px',
  },
  checkboxContainer: {
    marginTop: '16px',
    padding: '12px',
    background: tokens.colorNeutralBackground1,
    borderRadius: '6px',
    border: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  calculateButtonContainer: {
    display: 'flex',
    justifyContent: 'center',
    marginTop: '24px',
    paddingTop: '20px',
    borderTop: `1px solid ${tokens.colorNeutralStroke2}`,
  },
  calculateButton: {
    minWidth: '200px',
    height: '40px',
    fontSize: '16px',
    fontWeight: '600',
    background: `linear-gradient(135deg, ${tokens.colorBrandBackground} 0%, ${tokens.colorCompoundBrandBackground} 100%)`,
    color: tokens.colorNeutralForegroundOnBrand,
    border: 'none',
    borderRadius: '8px',
    boxShadow: '0 4px 12px rgba(0,0,0,0.15)',
    transition: 'all 0.2s ease',
    '&:hover': {
      background: `linear-gradient(135deg, ${tokens.colorCompoundBrandBackgroundHover} 0%, ${tokens.colorBrandBackgroundHover} 100%)`,
      boxShadow: '0 6px 16px rgba(0,0,0,0.2)',
      transform: 'translateY(-1px)',
    },
    '&:active': {
      transform: 'translateY(0)',
      boxShadow: '0 2px 8px rgba(0,0,0,0.15)',
    },
    '&:disabled': {
      background: tokens.colorNeutralBackground3,
      color: tokens.colorNeutralForeground3,
      boxShadow: 'none',
      transform: 'none',
    },
  },
  resultCard: {
    marginBottom: '24px',
    padding: '24px',
    background: `linear-gradient(135deg, ${tokens.colorNeutralBackground1} 0%, ${tokens.colorNeutralBackground2} 100%)`,
    borderRadius: '12px',
    border: `2px solid ${tokens.colorBrandStroke1}`,
    textAlign: 'center',
    boxShadow: '0 4px 16px rgba(0,0,0,0.08)',
  },
  resultLabel: {
    fontWeight: '600',
    color: tokens.colorNeutralForeground1,
    fontSize: '16px',
    marginBottom: '12px',
    display: 'block',
    letterSpacing: '0.3px',
  },
  resultValue: {
    fontSize: '42px',
    fontWeight: '700',
    color: tokens.colorBrandForeground1,
    background: tokens.colorNeutralBackground1,
    padding: '20px 32px',
    borderRadius: '10px',
    display: 'inline-block',
    minWidth: '140px',
    margin: '12px 0',
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  resultSubtext: {
    fontSize: '13px',
    color: tokens.colorNeutralForeground3,
    marginTop: '12px',
    lineHeight: '1.4',
  },
  loadingMessage: {
    marginBottom: '20px',
    padding: '16px',
    background: `linear-gradient(135deg, ${tokens.colorBrandBackground} 0%, ${tokens.colorNeutralBackground2} 100%)`,
    borderRadius: '8px',
    textAlign: 'center',
    fontSize: '15px',
    color: tokens.colorBrandForeground1,
    fontWeight: '500',
    border: `1px solid ${tokens.colorBrandStroke1}`,
  },
  formSection: {
    marginBottom: '0',
    background: tokens.colorNeutralBackground1,
    borderRadius: '10px',
    padding: '24px',
    boxShadow: '0 2px 8px rgba(0,0,0,0.06)',
    border: `1px solid ${tokens.colorNeutralStroke1}`,
  },
  buttonContainer: {
    display: 'flex',
    gap: '12px',
    justifyContent: 'flex-end',
  },
  errorCard: {
    marginBottom: '20px',
    padding: '20px',
    background: tokens.colorPaletteRedBackground1,
    borderRadius: '10px',
    border: `2px solid ${tokens.colorPaletteRedBorder1}`,
    textAlign: 'center',
    boxShadow: '0 2px 8px rgba(255,0,0,0.1)',
  },
  errorLabel: {
    fontWeight: '600',
    color: tokens.colorPaletteRedForeground1,
    fontSize: '15px',
    marginBottom: '8px',
    display: 'block',
  },
  errorValue: {
    fontSize: '14px',
    color: tokens.colorPaletteRedForeground2,
    lineHeight: '1.5',
  },
  settingsSection: {
    marginBottom: '20px',
  },
}); 